module.exports = db => {
    const funds = [
      {
        "name": "Jabair",
        "age": 32,
        "ocuppation": "Software-Developer",
        "birthday": "November 6 1989",
        "house-status": "Rent",
        "rent-cost": 1000,
        "yearly-net-income": 1000000,
        "requested-loan-amount": 500000,
      },
      {
        "name": "Franchesko",
        "age": 32,
        "ocuppation": "Software-Developer",
        "birthday": "July 9 1995",
        "house-status": "Rent",
        "rent-cost": 1000,
        "yearly-net-income": 1000000,
        "requested-loan-amount": 500000,
      },
      {
        "name": "Matt",
        "age": 32,
        "ocuppation": "Software-Developer",
        "birthday": "July 9 1995",
        "house-status": "Rent",
        "rent-cost": 1000,
        "yearly-net-income": 1000000,
        "requested-loan-amount": 500000,
      },
      {
        "name": "Lee",
        "age": 32,
        "ocuppation": "Software-Developer",
        "birthday": "July 9 1995",
        "house-status": "Rent",
        "rent-cost": 1000,
        "yearly-net-income": 1000000,
        "requested-loan-amount": 500000,
      },
      {
        "name": "Megan",
        "age": 32,
        "ocuppation": "Software-Developer",
        "birthday": "July 9 1995",
        "house-status": "Rent",
        "rent-cost": 1000,
        "yearly-net-income": 1000000,
        "requested-loan-amount": 500000,
      },
      {
        "name": "Evan",
        "age": 32,
        "ocuppation": "Software-Developer",
        "birthday": "July 9 1995",
        "house-status": "Rent",
        "rent-cost": 1000,
        "yearly-net-income": 1000000,
        "requested-loan-amount": 500000,
      },
      {
        "name": "Cody",
        "age": 32,
        "ocuppation": "Software-Developer",
        "birthday": "July 9 1995",
        "house-status": "Rent",
        "rent-cost": 1000,
        "yearly-net-income": 1000000,
        "requested-loan-amount": 500000,
      },
      {
        "name": "Omaid",
        "age": 32,
        "ocuppation": "Software-Developer",
        "birthday": "July 9 1995",
        "house-status": "Rent",
        "rent-cost": 1000,
        "yearly-net-income": 1000000,
        "requested-loan-amount": 500000,
      },

    ]
  
    funds.forEach(fund => db.funds.insert(fund))
  }
  